### ISSUE TITLE
Manually Handle/Store Exceptions

### ISSUE THREAD

**Issue by vanboom** [Sharagoz/rails_exception_handler#15]
Is it possible to store an exception that has been handled in a begin/rescue block?  For example:

```ruby
begin
  do_something_that_raises_an_exception
rescue => e
  RailsExceptionHandler::Handler.new(Rails.env, e).handle_exception
end
```

I tried calling handle_exception above and received this exception:

```
LoadError (Unable to autoload constant ErrorResponseController, expected /var/lib/gems/2.3.0/gems/rails_exception_handler-2.3.4/app/controllers/error_response_controller.rb to define it):
```

**Comment by Sharagoz** [comment]
There's a method for that, see: https://github.com/Sharagoz/rails_exception_handler/wiki/Manual-exception-handling-outside-of-rack

**Comment by vanboom** [comment]
Outstanding!  Thanks!
